version: "3.3"

services:
  personal-page:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3004:3004
    env_file:
      - int.env
    #networks:
    #  - webnet
